name: Create Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run validation
        run: npm run validate

      - name: Extract version from tag
        id: version
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Extract changelog entry
        id: changelog
        run: |
          # Extract the changelog section for this version
          VERSION=${{ steps.version.outputs.version }}
          CHANGELOG=$(sed -n "/## \[$VERSION\]/,/## \[/p" CHANGELOG.md | sed '$d')
          if [ -z "$CHANGELOG" ]; then
            CHANGELOG="Release $VERSION"
          fi
          # Use multiline output format
          {
            echo "notes<<EOF"
            echo "$CHANGELOG"
            echo "EOF"
          } >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release v${{ steps.version.outputs.version }}
          body: ${{ steps.changelog.outputs.notes }}
          draft: false
          prerelease: ${{ contains(steps.version.outputs.version, '-') }}
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build release artifacts
        run: |
          mkdir -p release
          tar -czf release/drawfish-v${{ steps.version.outputs.version }}.tar.gz \
            --exclude=node_modules \
            --exclude=.git \
            --exclude=.github \
            --exclude=release \
            --exclude=.env \
            .

      - name: Upload release artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: release/*.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release summary
        run: |
          echo "## Release v${{ steps.version.outputs.version }} Created Successfully" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Artifacts" >> $GITHUB_STEP_SUMMARY
          echo "- Docker Image: \`ghcr.io/${{ github.repository }}:v${{ steps.version.outputs.version }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- Source Archive: \`drawfish-v${{ steps.version.outputs.version }}.tar.gz\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Changelog" >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.changelog.outputs.notes }}" >> $GITHUB_STEP_SUMMARY
